// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wozbuzwxbmhrmnnhpuyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvemJ1end4Ym1ocm1ubmhwdXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjAxNjQsImV4cCI6MjA2NDQzNjE2NH0.wSZrJps_EU7eFOv9IlOhxiXe_VMUN2Onz5cowo-riDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);